- name: Initialize run environment for application Docker container
  hosts: all
  tasks:
    - name: Add Docker’s official GPG key
      become: yes
      apt_key:
        file: https://download.docker.com/linux/ubuntu/gpg
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
        state: present

    - name: Use Docker's own apt repository
      become: yes
      apt_repository:
        repo: 'deb https://apt.dockerproject.org/repo ubuntu-xenial main'
        state: present

    - name: Install Docker Community Edition, run apt update before installation
      become: yes
      apt:
        update_cache: yes
        pkg: docker-ce
        state: present

    - name: Install python-pip
      become: yes
      apt:
        pkg: python-pip
        state: present

    - name: Install latest docker-py version
      become: yes
      pip:
        name: docker-py
        extra_args: --upgrade

- name: Replace currently running application Docker container with deployed version
  hosts: all
  become: yes
  tasks:
    - name: Stop and remove current application Docker container
      docker_container:
        name: cde-demo-app
        state: absent

    - name: Start Docker container based on new application Docker image
      docker_container:
        name: cd-demo-app
        image: l3ku/cd-demo-app:{{ dockerImageVersion }}
        state: started
        ports:
         - "80:8888"
