- name: Install dependencies
  hosts: all
  tasks:
    - name: Update and upgrade apt packages
      become: yes
      apt:
        upgrade: yes
        update_cache: yes

    - name: Install python-pip
      become: yes
      apt: pkg=python-pip state=present

    - name: Update pip to latest version
      become: yes
      pip:
        name: pip
        extra_args: --upgrade

    - name: Install latest docker-py version
      become: yes
      pip:
        name: docker-py
        extra_args: --upgrade

- name: Remove current application instance
  hosts: all
  become: yes
  tasks:
    - name: Remove current application container
      docker_container:
        name: cde-demo-app
        state: absent

- name: Install and run new application
  hosts: all
  become: yes
  tasks:
    - name: Start l3ku/cde-demo-app Docker container
      docker_container:
        name: cde-demo-app
        image: l3ku/cde-demo-app
        pull: yes
        state: started
        ports:
         - "80:8888"
