- name: Install dependencies
  hosts: all
  tasks:
    - name: Update and upgrade apt packages
      become: yes
      apt:
        upgrade: yes
        update_cache: yes

    - name: Install python-pip
      become: yes
      apt: pkg=python-pip state=present

    - name: Install docker-py
      pip:
        name: docker-py

- name: Install Docker
  hosts: all
  tasks:
    - name: Install docker
      shell: curl -sSL https://get.docker.com | sh

    - name: Add current user to docker group
      become: yes
      user:
        name: ubuntu
        groups: docker
        append: yes

- name: Remove current application instance
  hosts: all
  tasks:
    - name: Remove current application container
      docker_container:
        name: cde-demo-app
        state: absent

- name: Install and run new application
  hosts: all
  tasks:
    - name: Start l3ku/cde-demo-app Docker container
      docker_container:
        name: cde-demo-app
        image: l3ku/cde-demo-app
        pull: yes
        state: started
        ports:
         - "80:8888"
